### ISSUE TITLE
Test suite fails when seed does not produce a counterexample

### ISSUE THREAD

**Issue by roberth** [snowleopard/selective#48]
In [this build](https://hercules-ci.com/accounts/github/hercules-ci/derivations/%2Fnix%2Fstore%2Flw12sq8bmyab2mh68fylldc3dhbl690r-selective-0.4.2.drv/log?via-job=a6105d19-7638-4e94-a4aa-13a1d6e716d9) (look for "previous attempt"), the test suite fails and logs:

```
        Use --quickcheck-replay=116302 to reproduce. (expected failure)
       Interchange: (x *> (y <*? z)) == ((x *> y) <*? z):                                                                    OK (unexpected)
         +++ OK, passed 100 tests.
          (unexpected success)
         Use -p '/Validation.Theorems.Interchange: (x *> (y <*? z)) == ((x *> y) <*? z)/' to rerun this test only.
```

This is `theorem6` in `validationTheorems :: Tests`, which is an `expectFailure` test. This means that it is using a property test to find a counterexample for the interchange theorem. If it fails to find one, it fails the test suite.

Failing the test suite doesn't seem like the right thing to do here, because the absence of such a property can hardly be a requirement for the library to function correctly.

**Comment by snowleopard** [comment]
Thanks, I agree. This also annoyed me a few times. I guess we have two options here:

* Make an unexpected success a warning, i.e. do not fail the test suite when it happens. 

* Instead of using the expected failures mechanism, record counterexamples in the test suite (the test suite would simply ensure that counter-examples indeed violate the corresponding properties).

The first option is easier to implement. The second one seems like a better solution.

**Comment by snowleopard** [comment]
I'll try to find time to implement one of the two options soon. Happy to review a PR if anyone beats me to it!
